### ISSUE TITLE
MultiOTP Wiki Page Out of Date

### ISSUE THREAD

**Issue by nabber00** [LastSquirrelIT/MultiOneTimePassword-CredentialProvider#12]
The core problem is this:

"Windows account name is john and we dont want -prefix-pin. "

-prefix-pin is now the default.  Running the example command will indeed set a pin.  The documentation states that PINs are now the default and should be disabled with the -set option.  For example, this clears the PIN requirement now:

multiotp.exe -debug -set john pin=

**Comment by DominikPretzsch** [comment]
Thank you for the hint. Changed it accordingly.
