### ISSUE TITLE
PrivacyIDEA + Windows 8

### ISSUE THREAD

**Issue by borschoff** [LastSquirrelIT/MultiOneTimePassword-CredentialProvider#17]
Hello Dominik!

In my test environment i have:
- privacyIDEA 2.8.1 
- Windows 8.1 Desktop (with disabled FW)
- AD user
- Installed on desktop MultiOneTimePassword-CredentialProvider

I've trying to make config as it describeed on this video:
https://www.youtube.com/watch?v=Mpc73d7wACQ
In server address i have set https://ip_addres/

After rebooting i've try to login with multiOTP, but there is an error 80004005.
In privacyIDEA server user audit log i haven't found any actions from this host\user

What i've done wrong?

**Comment by DominikPretzsch** [comment]
Hi,

you are using the wrong CP.

The privacyIdea CP is not available publicly, yet.
Please contact me at dominik.pretzsch@lastsquirrel.com, so I can send you a
download link for the privacyIdea CP.

Best regards

Dominik Pretzsch

2016-02-16 13:15 GMT+01:00 borschoff <notifications@github.com>:

> Hello Dominik!
>
> In my test environment i have:
>
>    - privacyIDEA 2.8.1
>    - Windows 8.1 Desktop (with disabled FW)
>    - AD user
>    - Installed on desktop MultiOneTimePassword-CredentialProvider
>
> I've trying to make config as it describeed on this video:
> https://www.youtube.com/watch?v=Mpc73d7wACQ
> In server address i have set https://ip_addres/
>
> After rebooting i've try to login with multiOTP, but there is an error
> 80004005.
> In privacyIDEA server user audit log i haven't found any actions from this
> host\user
>
> What i've done wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/17>
> .
>

-- 


Last Squirrel IT 
Dominik Pretzsch

Humboldtstr. 2
09130 Chemnitz, Germany

USt-IdNr.: DE290444313


*******************************************************************************
Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte 
Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich 
erhalten
haben, informieren Sie bitte sofort den Absender und vernichten Sie diese 
Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist 
nicht
gestattet.

This email may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this email
in error) please notify the sender immediately and destroy this email.
Any unauthorized copying, disclosure or distribution of the material
in this email is strictly forbidden.
*******************************************************************************

**Comment by borschoff** [comment]
Ok, thank you Dominik!
