### ISSUE TITLE
Domain Users

### ISSUE THREAD

**Issue by waterloopa** [LastSquirrelIT/MultiOneTimePassword-CredentialProvider#2]
Hi,

When logging on as a domain user, you have to enter domainname\username otherwise you cannot be authenticated. Is there a way to rectify this.

We are running it on server 2012r2.

Thanks

**Comment by waterloopa** [comment]
Any update on this and images I sent?

**Comment by DominikPretzsch** [comment]
Hi,

sorry for the delay. I'll update the provider the next days!

Dominik Pretzsch

2015-01-01 21:51 GMT+01:00 waterloopa <notifications@github.com>:

> Any update on this and images I sent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/2#issuecomment-68497874>
> .
>

-- 


Last Squirrel IT 
Dominik Pretzsch

Humboldtstr. 2
09130 Chemnitz, Germany

USt-IdNr.: DE290444313


*******************************************************************************
Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte 
Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich 
erhalten
haben, informieren Sie bitte sofort den Absender und vernichten Sie diese 
Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist 
nicht
gestattet.

This email may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this email
in error) please notify the sender immediately and destroy this email.
Any unauthorized copying, disclosure or distribution of the material
in this email is strictly forbidden.
*******************************************************************************
