### ISSUE TITLE
Default Provider and user without OTP

### ISSUE THREAD

**Issue by steakikan** [LastSquirrelIT/MultiOneTimePassword-CredentialProvider#5]
Hi, can the user still login without OTP if the user doesn't want it but we set the default credential provider to MOTP-CP? Because I tried to login for the user without OTP and always fail.

**Comment by DominikPretzsch** [comment]
Hi steakikan,

thank you for your request.

No, using this CP it's not possible to logon without OTP. This is intended
behaviour, as allowing this would open an attack vector.


Best regards

Dominik Pretzsch

2015-03-16 4:41 GMT+01:00 steakikan <notifications@github.com>:

> Hi, can the user still login without OTP if the user doesn't want it but
> we set the default credential provider to MOTP-CP? Because I tried to login
> for the user without OTP and always fail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/5>
> .
>

-- 


Last Squirrel IT 
Dominik Pretzsch

Humboldtstr. 2
09130 Chemnitz, Germany

USt-IdNr.: DE290444313


*******************************************************************************
Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte 
Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich 
erhalten
haben, informieren Sie bitte sofort den Absender und vernichten Sie diese 
Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist 
nicht
gestattet.

This email may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this email
in error) please notify the sender immediately and destroy this email.
Any unauthorized copying, disclosure or distribution of the material
in this email is strictly forbidden.
*******************************************************************************
