### ISSUE TITLE
Cannot login -have installed mOTP-CP without mOTP

### ISSUE THREAD

**Issue by epatels** [LastSquirrelIT/MultiOneTimePassword-CredentialProvider#6]
I have by mistake installed mOTP-CP without the mOTP.
How I am stuck at the login screen. I do not have the OTP to enter windows.
Desperate for the help.
Thanks

**Comment by DominikPretzsch** [comment]
Don't panic! Reboot to safe mode, if you did not activate the CP for safe
mode, too. :)

Dominik Pretzsch

2015-04-09 6:30 GMT+02:00 epatels <notifications@github.com>:

> I have by mistake installed mOTP-CP without the mOTP.
> How I am stuck at the login screen. I do not have the OTP to enter windows.
> Desperate for the help.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/6>
> .
>

-- 


Last Squirrel IT 
Dominik Pretzsch

Humboldtstr. 2
09130 Chemnitz, Germany

USt-IdNr.: DE290444313


*******************************************************************************
Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte 
Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich 
erhalten
haben, informieren Sie bitte sofort den Absender und vernichten Sie diese 
Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist 
nicht
gestattet.

This email may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this email
in error) please notify the sender immediately and destroy this email.
Any unauthorized copying, disclosure or distribution of the material
in this email is strictly forbidden.
*******************************************************************************

**Comment by epatels** [comment]
Thanks, will try and revert back

Regards,
Chandrakant Patel
----------------------------------------------------------

**Comment by epatels** [comment]
Dear Dominik

Thanks for your inputs. It helped solve the problem, by uninstalling
mOTP-CP. Only additional step required was enabling windows installer
service by tweaking the registry, which was not difficult.

Further, may I take this opportunity to ask you whether the mOTP would work
in following environments;
1) Windows 8.1 standalone
2) Windows 2003 Server
3) Windows 2012 R2 Server
4) Windows 8.1 as client of any windows server.

Hope, I did not trouble you a lot.

Thanks and Regards,
Chandrakant Patel
----------------------------------------------------------

**Comment by DominikPretzsch** [comment]
Hello Chandrakant,

no problem at all. Good to hear it's working again.


The CP works for all mentioned, except Server 2003.

Dominik Pretzsch

2015-04-09 17:12 GMT+02:00 epatels <notifications@github.com>:

> Dear Dominik
>
> Thanks for your inputs. It helped solve the problem, by uninstalling
> mOTP-CP. Only additional step required was enabling windows installer
> service by tweaking the registry, which was not difficult.
>
> Further, may I take this opportunity to ask you whether the mOTP would work
> in following environments;
> 1) Windows 8.1 standalone
> 2) Windows 2003 Server
> 3) Windows 2012 R2 Server
> 4) Windows 8.1 as client of any windows server.
>
> Hope, I did not trouble you a lot.
>
> Thanks and Regards,
> Chandrakant Patel
> ----------------------------------------------------------
>
> On Thu, Apr 9, 2015 at 6:59 PM, C K Patel <mail@ckpatel.com> wrote:
>
> > Thanks, will try and revert back
> >
> > Regards,
> > Chandrakant Patel
> > ----------------------------------------------------------
> >
> > On Thu, Apr 9, 2015 at 6:45 PM, DominikPretzsch <
> notifications@github.com>
> > wrote:
> >
> >> Don't panic! Reboot to safe mode, if you did not activate the CP for
> safe
> >> mode, too. :)
> >>
> >> Dominik Pretzsch
> >>
> >> 2015-04-09 6:30 GMT+02:00 epatels <notifications@github.com>:
> >>
> >> > I have by mistake installed mOTP-CP without the mOTP.
> >> > How I am stuck at the login screen. I do not have the OTP to enter
> >> windows.
> >> > Desperate for the help.
> >> > Thanks
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/6
> >> >
> >> > .
> >> >
> >>
> >> --
> >>
> >>
> >> Last Squirrel IT
> >> Dominik Pretzsch
> >>
> >> Humboldtstr. 2
> >> 09130 Chemnitz, Germany
> >>
> >> USt-IdNr.: DE290444313
> >>
> >>
> >>
> >>
> *******************************************************************************
> >> Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte
> >> Informationen.
> >> Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich
> >> erhalten
> >> haben, informieren Sie bitte sofort den Absender und vernichten Sie
> diese
> >> Mail.
> >> Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist
> >> nicht
> >> gestattet.
> >>
> >> This email may contain confidential and/or privileged information.
> >> If you are not the intended recipient (or have received this email
> >> in error) please notify the sender immediately and destroy this email.
> >> Any unauthorized copying, disclosure or distribution of the material
> >> in this email is strictly forbidden.
> >>
> >>
> *******************************************************************************
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/6#issuecomment-91228605
> >
>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LastSquirrelIT/MultiOneTimePassword-CredentialProvider/issues/6#issuecomment-91260166>
> .
>

-- 


Last Squirrel IT 
Dominik Pretzsch

Humboldtstr. 2
09130 Chemnitz, Germany

USt-IdNr.: DE290444313


*******************************************************************************
Diese E-Mail enthaelt vertrauliche und/oder rechtlich geschuetzte 
Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtuemlich 
erhalten
haben, informieren Sie bitte sofort den Absender und vernichten Sie diese 
Mail.
Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser E-Mail ist 
nicht
gestattet.

This email may contain confidential and/or privileged information.
If you are not the intended recipient (or have received this email
in error) please notify the sender immediately and destroy this email.
Any unauthorized copying, disclosure or distribution of the material
in this email is strictly forbidden.
*******************************************************************************
